### ISSUE TITLE
MOV (video/quicktime) doesnt grab the first frame

### ISSUE THREAD

**Issue by stuntnmore** [theatlantic/thumbor-video-engine#9]
It seems like MOV is not supported when grabbing a still() frame from a URL, is there any fix or workaround? mp4 and everything else works fine

**Comment by stuntnmore** [comment]
> Could you provide an example mov file?

Sent you an email with the example and url that was used

**Comment by fdintino** [comment]
I think this should be fixed in v1.2.2, which I just uploaded to PyPi.

**Comment by stuntnmore** [comment]
Just did an upgrade to latest v1.2.2, still facing the issue on the still image not grabbing the frame on mov
